//
//  CalculatePresenter.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculatePresentationLogic {
    func presentGetCurrencyDetail(response: Calculate.CurrencyDetail.Response)
    func presentCalculate(response: Calculate.Calculate.Response)
}

class CalculatePresenter: CalculatePresentationLogic {
    weak var viewController: CalculateDisplayLogic?
    
    // MARK: Do something
    
    func presentGetCurrencyDetail(response: Calculate.CurrencyDetail.Response) {
        let viewModel = Calculate.CurrencyDetail.ViewModel(title: "\(response.code) convert to BTC",
                                                           code: response.code)
        viewController?.displayGetCurrencyDetail(viewModel: viewModel)
    }
    
    func presentCalculate(response: Calculate.Calculate.Response) {
        let viewModel = Calculate.Calculate.ViewModel(resultDisplay: "\(response.resultRate) BTC")
        viewController?.displayCalculate(viewModel: viewModel)
    }
}
