//
//  CalculateInteractor.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CalculateBusinessLogic {
    func doGetCurrencyDetail(request: Calculate.CurrencyDetail.Request)
    func doCalculate(request: Calculate.Calculate.Request)
}

protocol CalculateDataStore {
    var code: String? { get set }
    var rate: Double? { get set }
}

class CalculateInteractor: CalculateBusinessLogic, CalculateDataStore {
    var presenter: CalculatePresentationLogic?
    var worker: CalculateWorker?
    
    var code: String?
    var rate: Double?
    
    // MARK: Do something
    
    func doGetCurrencyDetail(request: Calculate.CurrencyDetail.Request) {
        let response = Calculate.CurrencyDetail.Response(code: code ?? "")
        presenter?.presentGetCurrencyDetail(response: response)
    }
    
    func doCalculate(request: Calculate.Calculate.Request) {
        let resultRate = request.number / (rate ?? 0)
        let response = Calculate.Calculate.Response(resultRate: resultRate)
        presenter?.presentCalculate(response: response)
    }
}
