//
//  CalculateModels.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Calculate
{
  // MARK: Use cases
  
  enum CurrencyDetail {
    struct Request {
    }
    struct Response {
        var code: String
    }
    struct ViewModel {
        var title: String
        var code: String
    }
  }
    
    enum Calculate {
      struct Request {
          var number: Double
      }
      struct Response {
          var resultRate: Double
      }
      struct ViewModel {
          var resultDisplay: String
      }
    }
}
