//
//  BTCSceneModels.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BTCScene {
    // MARK: Use cases
    
    enum GetBTC {
        struct Request {
        }
        struct Response {
            var btcRate: CurrentPriceResponse?
        }
        struct ViewModel {
            var usdTitle: String
            var usdDescription: String
            var usdRate: String
            
            var gbpTitle: String
            var gbpDescription: String
            var gbpRate: String
            
            var eurTitle: String
            var eurDescription: String
            var eurRate: String
        }
    }
}
