//
//  HistoryPresenter.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryPresentationLogic {
    func presentGetHistory(response: History.GetHistory.Response)
}

class HistoryPresenter: HistoryPresentationLogic {
    weak var viewController: HistoryDisplayLogic?
    
    // MARK: Do something
    
    func presentGetHistory(response: History.GetHistory.Response) {
        let viewModel = History.GetHistory.ViewModel(historyList: response.historyList)
        viewController?.displayGetHistory(viewModel: viewModel)
    }
}
