//
//  HistoryInteractor.swift
//  Test
//
//  Created by Ratchapol Pattarakanoksiri on 17/5/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HistoryBusinessLogic {
    func doGetHistory(request: History.GetHistory.Request)
}

protocol HistoryDataStore {
    var btcHistoryList: [BTCHistoryModel] { get set }
}

class HistoryInteractor: HistoryBusinessLogic, HistoryDataStore {
    var presenter: HistoryPresentationLogic?
    var worker: HistoryWorker?
    var btcHistoryList: [BTCHistoryModel] = []
    
    // MARK: Do something
    
    func doGetHistory(request: History.GetHistory.Request) {
        let response = History.GetHistory.Response(historyList: btcHistoryList)
        presenter?.presentGetHistory(response: response)
    }
}
